apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize

helmCharts:
  - name: my-python-app
#    repo: https://manabpokhrel7.github.io can use repo if the helm chart is in another repo
    path: ../../helm-kustomize
    version: 1.0.0
    valuesFile: values.yaml           # Base overrides
    additionalValuesFiles:
      - ../../helm-kustomize/env/dev/values.yaml                # Dev-specific overrides (highest priority)

