apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      manab: pokhrel
      kishna: khadayat
    includeSelectors: true
    includeTemplates: true # Ensures Pods also get these labels

helmGlobals:
  chartHome: ../../.. # Path from base to manifest folder which is helm-kustomize folder which contains your helm charts

helmCharts:
- name: helm-kustomize
  releaseName: v1
  valuesFile: ../../../helm-kustomize/values.yaml
  additionalValuesFiles:
    - ../../../helm-kustomize/env/dev/values.yaml