apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding